# Generated by Django 5.2.3 on 2025-07-01 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngelOneSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=100)),
                ('auth_token', models.TextField(blank=True)),
                ('feed_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('session_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='angel_api_a_endpoin_011782_idx'), models.Index(fields=['status_code', '-created_at'], name='angel_api_a_status__61a79d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NSESymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('lot_size', models.IntegerField(default=1)),
                ('instrument_type', models.CharField(default='EQ', max_length=20)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('isin', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ltp', models.DecimalField(decimal_places=2, help_text='Last Traded Price', max_digits=12)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_timestamp', models.DateTimeField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='angel_api.nsesymbol')),
            ],
            options={
                'ordering': ['-data_timestamp'],
                'indexes': [models.Index(fields=['symbol', '-data_timestamp'], name='angel_api_m_symbol__65bbb9_idx'), models.Index(fields=['-data_timestamp'], name='angel_api_m_data_ti_58a81f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL', 'Stop Loss'), ('SL-M', 'Stop Loss Market')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.CharField(default='CNC', max_length=20)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('duration', models.CharField(default='DAY', max_length=10)),
                ('angel_order_id', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='angel_api.nsesymbol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='angel_api_o_symbol__886e63_idx'), models.Index(fields=['status', '-created_at'], name='angel_api_o_status_ca6fc4_idx'), models.Index(fields=['transaction_type', '-created_at'], name='angel_api_o_transac_4578bb_idx')],
            },
        ),
    ]
