# Generated by Django 5.2.3 on 2025-07-01 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angel_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Portfolio', max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unrealized_pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='angel_api.nsesymbol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'is_open'], name='portfolio_p_portfol_45c761_idx'), models.Index(fields=['symbol', 'is_open'], name='portfolio_p_symbol__94b7c3_idx')],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('brokerage_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL', 'Stop Loss'), ('SL-M', 'Stop Loss Market')], default='MARKET', max_length=20)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='EXECUTED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('holding_days', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.portfolio')),
                ('ref_trade', models.ForeignKey(blank=True, help_text='Reference to the original buy trade for sell trades', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.trade')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='angel_api.nsesymbol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'symbol', '-created_at'], name='portfolio_t_portfol_111834_idx'), models.Index(fields=['action', '-created_at'], name='portfolio_t_action_27a852_idx'), models.Index(fields=['status', '-created_at'], name='portfolio_t_status_1b4233_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('profitable_trades', models.IntegerField(default=0)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
                'indexes': [models.Index(fields=['portfolio', 'session_date'], name='portfolio_t_portfol_bae6f3_idx'), models.Index(fields=['is_active', '-session_date'], name='portfolio_t_is_acti_6b3908_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angel_api.nsesymbol')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.watchlist')),
            ],
            options={
                'ordering': ['-priority', 'symbol__symbol'],
                'unique_together': {('watchlist', 'symbol')},
            },
        ),
    ]
